name: deploy-ci-cd

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up environment variables
        run: |
            echo "NEXT_PUBLIC_USER_API=${{ secrets.NEXT_PUBLIC_USER_API }}" >> .env
            echo "NEXT_PUBLIC_MOVIE_API=${{ secrets.NEXT_PUBLIC_MOVIE_API }}" >> .env

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: iamqbao/gauphimv2:latest

#      - name: Trigger deployment via SSH
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SERVER_HOST }}
#          username: ${{ secrets.SERVER_USER }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          script: |
#            cd ~/.operator
#            sh restart_gauphimv2.sh
